# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: acachecontrol
  version: "0.3.6"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/MasterSergius/acachecontrol/archive/v${{ version }}.tar.gz
  sha256: 2eda68cdce88561684fbeef9cb221322e5eb8427ea929ab27342b7de279a5554

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }},<4.0
    - aiohttp >=3.10.2
    - setuptools >=38.0

tests:
  - python:
      imports:
        - acachecontrol
      python_version: ${{ python_min }}.*
      pip_check: true

about:
  summary: Cache-Control for aiohttp
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/MasterSergius/acachecontrol

extra:
  recipe-maintainers:
    - rxm7706
