# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: acachecontrol
  version: 0.3.7

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/MasterSergius/acachecontrol/archive/v${{ version }}.tar.gz
  sha256: 186e85ddd0d1b374f4828883e0d13581c4162a07363172fb87b99bd456085ec6

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }},<4.0
    - aiohttp >=3.10.2
tests:
  - python:
      imports:
        - acachecontrol
      python_version: ${{ python_min }}.*
      pip_check: true

about:
  summary: Cache-Control for aiohttp
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/MasterSergius/acachecontrol

extra:
  recipe-maintainers:
    - rxm7706
